name: Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger deployment only on main branch pushes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image
      uses: azure/docker-login@v1
      with:
        login-server: docintelai.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t docintelai.azurecr.io/my-app:latest .
        docker push docintelai.azurecr.io/my-app:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: docintelai  # Replace with your Azure App Service name
        images: docintelai.azurecr.io/my-app:latest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
