name: Run API Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx python-dotenv

      - name: Load Environment Variables
        run: |
          cp .env.example .env  # Ensure CI has the correct environment variables

      - name: Start FastAPI
        run: |
          nohup uvicorn ChatbotAPI:app --host 0.0.0.0 --port 8000 & 
          sleep 5  # Give it time to start

      - name: Run Tests with pytest
        run: pytest --maxfail=1 --disable-warnings --tb=short

